# Generated by Django 5.2.11 on 2026-03-26 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branches_head_commit'),
        ('storage', '0002_treenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree', to='branches.commit')),
            ],
        ),
    ]
