# Generated by Django 5.2.11 on 2026-03-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenode',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='storage.tree'),
        ),
    ]
