# Generated by Django 5.2.11 on 2026-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_treenode_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='is_binary',
            field=models.BooleanField(default=False),
        ),
    ]
