# Generated by Django 5.2.11 on 2026-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='verb',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
