# Generated by Django 5.2.10 on 2026-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="labels",
            field=models.ManyToManyField(blank=True, null=True, to="issues.label"),
        ),
    ]
