# Generated by Django 5.2.10 on 2026-02-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_alter_issue_labels"),
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="repo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="repositories.repository",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="labels",
            field=models.ManyToManyField(blank=True, to="issues.label"),
        ),
    ]
