# Generated by Django 5.2.11 on 2026-02-23 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='head_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.commit'),
        ),
    ]
