REPO_ADMIN = "admin"
REPO_MAINTAINER = "maintainer"
REPO_MEMBER = "member"
REPO_VIEWER = "viewer"

REPO_ROLLS = {
    REPO_ADMIN,
    REPO_MAINTAINER,
    REPO_MEMBER,
    REPO_VIEWER
}

DELETE_REPO = "DELETE_REPO"
UPDATE_REPO = "UPDATE_REPO"
CREATE_REPO = "CREATE_REPO"
MERGE_PR = "MERGE_PR"
INVITE_USER = "INVITE_USER"
REMOVE_USER = "REMOVE_USER"
LEAVE_REPO = "LEAVE_REPO"
CREATE_PR = "CREATE_PR"
CREATE_ISSUE = "CREATE_ISSUE"
CLOSE_ISSUE = "CLOSE_ISSUE"
COMMENT = "COMMENT"

# Branch actions
CREATE_BRANCH = "CREATE_BRANCH"
DELETE_BRANCH = "DELETE_BRANCH"
PROTECT_BRANCH = "PROTECT_BRANCH"


ROLE_PRIORITY = {
    REPO_ADMIN : 4,
    REPO_MAINTAINER : 3,
    REPO_MEMBER : 2,
    REPO_VIEWER : 1
}

REPO_ACTIONS = {
    DELETE_REPO,
    UPDATE_REPO,
    CREATE_REPO,
    MERGE_PR,
    INVITE_USER,
    REMOVE_USER,
    LEAVE_REPO,
    CREATE_PR,
    CREATE_ISSUE,
    CLOSE_ISSUE,
    COMMENT,
    CREATE_BRANCH,
    DELETE_BRANCH,
    PROTECT_BRANCH,
}


REPO_ADMIN_ACTIONS = {
    DELETE_REPO,
    UPDATE_REPO,
    INVITE_USER,
    REMOVE_USER,
}

COLLABORATOR_ACTIONS = {
    MERGE_PR,
    CREATE_PR,
    CREATE_ISSUE,
    CLOSE_ISSUE,
    COMMENT,
    CREATE_BRANCH,
}

MAINTAINER_ACTIONS = {
    MERGE_PR,
    CREATE_PR,
    CREATE_ISSUE,
    CLOSE_ISSUE,
    COMMENT,
    CREATE_BRANCH,
    DELETE_BRANCH,
}

