# Generated by Django 5.2.11 on 2026-02-16 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0001_initial'),
        ('branches', '0001_initial'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequestcomment',
            old_name='user',
            new_name='reviewer',
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repo', 'source_branch', 'target_branch')},
        ),
        migrations.AlterUniqueTogether(
            name='pullrequestcomment',
            unique_together={('pr', 'reviewer', 'comment')},
        ),
    ]
