# Generated by Django 5.2.11 on 2026-02-16 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0002_rename_user_pullrequestcomment_reviewer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequestcomment',
            old_name='reviewer',
            new_name='commenter',
        ),
        migrations.AlterUniqueTogether(
            name='pullrequestcomment',
            unique_together={('pr', 'commenter', 'comment')},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('COMMENTED', 'Commented')], max_length=20)),
                ('comment', models.TextField()),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='PullRequest.pullrequest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
