# Generated by Django 5.2.11 on 2026-02-16 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0003_rename_reviewer_pullrequestcomment_commenter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('pr', 'reviewer')},
        ),
    ]
