# Generated by Django 5.2.11 on 2026-02-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0004_alter_review_unique_together'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='target_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='source_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_pull_requests', to='branches.branches'),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='target_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_pull_requests', to='branches.branches'),
        ),
    ]
