# Generated by Django 5.2.11 on 2026-02-23 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0006_alter_pullrequest_merged_by_alter_pullrequest_status_and_more'),
        ('branches', '0003_branches_head_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='base_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_for_prs', to='branches.commit'),
        ),
    ]
