# Generated by Django 5.2.11 on 2026-02-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0007_pullrequest_base_commit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PullRequestComment',
        ),
    ]
