# Generated by Django 5.2.11 on 2026-03-21 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0008_delete_pullrequestcomment'),
        ('branches', '0003_branches_head_commit'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('repo', 'source_branch', 'target_branch'), name='unique_open_pr_per_branch_pair'),
        ),
    ]
