# Generated by Django 5.2.11 on 2026-03-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0009_alter_pullrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='commit',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
