# Generated by Django 5.2.11 on 2026-03-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0010_review_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='diff_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='precomputed_diff',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
