# Generated by Django 5.2.11 on 2026-04-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0011_pullrequest_diff_status_pullrequest_precomputed_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
