# Generated by Django 5.2.11 on 2026-05-25 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullRequest', '0012_alter_pullrequest_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PullRequestViewedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('viewed', models.BooleanField(default=True)),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_files', to='PullRequest.pullrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_viewed_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pr', 'user', 'file_path'), name='unique_pr_user_viewed_file_path')],
            },
        ),
    ]
