# Generated by Django 5.2.11 on 2026-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='side',
            field=models.CharField(blank=True, choices=[('old', 'Old'), ('new', 'New')], max_length=10, null=True),
        ),
    ]
