# Generated by Django 5.2.11 on 2026-03-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_file'),
    ]

    operations = [
    ]
